/**
 * Reads scripts/geo-data/manifest.json and writes src/generated/geoRegistry.ts.
 *
 * Usage:
 *   npm run geo:build       # runs all three generators including this one
 *   tsx scripts/geo/generateRegistry.ts   # run standalone
 */

import * as fs from 'fs';
import * as path from 'path';

const root = path.resolve(import.meta.dirname, '../..');
const manifestPath = path.join(root, 'scripts/geo-data/manifest.json');
const outputPath = path.join(root, 'src/generated/geoRegistry.ts');

// ---------------------------------------------------------------------------
// Read manifest
// ---------------------------------------------------------------------------

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as {
  cities: Array<{
    id: string;
    label: string;
    geojson: string | null;
    labeledSvgOverride?: string;
    blankSvgOverride?: string;
    defaultDifficulty: number;
    diagonalKm: number | null;
    group: string;
  }>;
  regions: Array<{
    id: string;
    label: string;
  }>;
};

// ---------------------------------------------------------------------------
// Build LANDMARK_MAP_CONFIG
// ---------------------------------------------------------------------------

const landmarkEntries: Record<string, object> = {};
for (const entry of manifest.cities) {
  const config: Record<string, unknown> = {
    label: entry.label,
    dataUrl: `/data/landmarks/${entry.id}.json`,
    labeledSvg: entry.geojson === null
      ? entry.labeledSvgOverride
      : `/images/maps/${entry.id}_labeled.svg`,
    blankSvg: entry.geojson === null
      ? entry.blankSvgOverride
      : `/images/maps/${entry.id}_blank.svg`,
    defaultDifficulty: entry.defaultDifficulty,
  };
  if (entry.diagonalKm !== null) {
    config.diagonalKm = entry.diagonalKm;
  }
  landmarkEntries[entry.id] = config;
}

// ---------------------------------------------------------------------------
// Build REGION_MAP_CONFIG
// ---------------------------------------------------------------------------

const regionEntries: Record<string, object> = {};
for (const entry of manifest.regions) {
  regionEntries[entry.id] = {
    label: entry.label,
    dataUrl: `/data/regions/${entry.id}.json`,
    boundariesSvg: `/images/maps/${entry.id}_boundaries.svg`,
    outlineSvg: `/images/maps/${entry.id}_outline.svg`,
  };
}

// ---------------------------------------------------------------------------
// Build CITY_GROUPS (preserve insertion order from manifest)
// ---------------------------------------------------------------------------

const groupMap = new Map<string, string[]>();
for (const entry of manifest.cities) {
  if (!groupMap.has(entry.group)) groupMap.set(entry.group, []);
  groupMap.get(entry.group)!.push(entry.id);
}
const cityGroups = Array.from(groupMap.entries()).map(([label, keys]) => ({ label, keys }));

// ---------------------------------------------------------------------------
// Build REGION_MAPS
// ---------------------------------------------------------------------------

const regionMaps = manifest.regions.map((r) => ({ key: r.id, label: r.label }));

// ---------------------------------------------------------------------------
// Write generated file
// ---------------------------------------------------------------------------

function fmt(obj: unknown): string {
  return JSON.stringify(obj, null, 2);
}

const output = `\
// DO NOT EDIT — generated by \`npm run geo:build\`
// Source of truth: scripts/geo-data/manifest.json

import type { LandmarkMapConfig } from '../data/landmarkMapConfig';
import type { RegionMapConfig } from '../data/regionMapConfig';

export const LANDMARK_MAP_CONFIG: Record<string, LandmarkMapConfig> = ${fmt(landmarkEntries)};

export const REGION_MAP_CONFIG: Record<string, RegionMapConfig> = ${fmt(regionEntries)};

export const CITY_GROUPS: { label: string; keys: string[] }[] = ${fmt(cityGroups)};

export const REGION_MAPS: { key: string; label: string }[] = ${fmt(regionMaps)};
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
console.log('Written: src/generated/geoRegistry.ts');
